{
 "title": "YugaByte",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "store_id", "query": "1,2,3,4,5,6,7,8,9,10" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select time, (total_sale/1000000) total_sale\nFROM ( \nSELECT\n  window_start AS \"time\",\n  total_sale,\n  rank() over (partition by store_id order by window_start desc) r \nFROM summary\nWHERE\n  $__timeFilter(window_start) and store_id is null and product_name is null\n) a\nwhere r = 1"
    }
   ]
  },
  {
   "title": "Latest Store Sales (mn $)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select cast(a.store_id as text), a.total_sale/1000000\nfrom (select *, rank() over (partition by store_id order by window_start desc) latest_sales  \n      from summary \n      where product_name is null \n      and store_id is not null) a  \nwhere latest_sales = 1\norder by 2 desc"
    }
   ]
  },
  {
   "title": "Store Sales Trend (mn $)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  window_start AS \"time\",\n  total_sale as \"Store 1\"\nFROM summary\nWHERE\n  $__timeFilter(window_start) and store_id = 1 and product_name is null\nORDER BY 1,2\nlimit 15"
    },
    {
     "rawSql": "SELECT\n  window_start AS \"time\",\n  total_sale as \"Store 2\"\nFROM summary\nWHERE\n  $__timeFilter(window_start) and store_id = 2 and product_name is null\nORDER BY 1,2\nlimit 15"
    },
    {
     "rawSql": "SELECT\n  window_start AS \"time\",\n  total_sale as \"Store 3\"\nFROM summary\nWHERE\n  $__timeFilter(window_start) and store_id = 3 and product_name is null\nORDER BY 1,2\nlimit 15"
    },
    {
     "rawSql": "SELECT\n  window_start AS \"time\",\n  total_sale as \"Store 4\"\nFROM summary\nWHERE\n  $__timeFilter(window_start) and store_id = 4 and product_name is null\nORDER BY 1,2\nlimit 15"
    },
    {
     "rawSql": "SELECT\n  window_start AS \"time\",\n  total_sale as \"Store 5\"\nFROM summary\nWHERE\n  $__timeFilter(window_start) and store_id = 5 and product_name is null\nORDER BY 1,2\nlimit 15"
    },
    {
     "rawSql": "SELECT\n  window_start AS \"time\",\n  total_sale as \"Store 7\"\nFROM summary\nWHERE\n  $__timeFilter(window_start) and store_id = 7 and product_name is null\nORDER BY 1,2\nlimit 15"
    },
    {
     "rawSql": "SELECT\n  window_start AS \"time\",\n  total_sale as \"Store 6\"\nFROM summary\nWHERE\n  $__timeFilter(window_start) and store_id = 6 and product_name is null\nORDER BY 1,2\nlimit 15"
    },
    {
     "rawSql": "SELECT\n  window_start AS \"time\",\n  total_sale as \"Store 8\"\nFROM summary\nWHERE\n  $__timeFilter(window_start) and store_id = 8 and product_name is null\nORDER BY 1,2\nlimit 15"
    },
    {
     "rawSql": "SELECT\n  window_start AS \"time\",\n  total_sale as \"Store 9\"\nFROM summary\nWHERE\n  $__timeFilter(window_start) and store_id = 9 and product_name is null\nORDER BY 1,2\nlimit 15"
    },
    {
     "rawSql": "SELECT\n  window_start AS \"time\",\n  total_sale as \"Store 10\"\nFROM summary\nWHERE\n  $__timeFilter(window_start) and store_id = 10 and product_name is null\nORDER BY 1,2\nlimit 15"
    }
   ]
  },
  {
   "title": "Top Products for Store - ${store_id}",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select product_name as \"Product\", (total_sale/1000000.0) as \"Total Sale(mn $)\"\nFROM ( \nSELECT\n  window_start AS \"time\",\n  product_name,\n  total_sale,\n  rank() over (partition by store_id order by window_start desc) r \nFROM summary\nWHERE\n  $__timeFilter(window_start) and store_id = ${store_id} and product_name is not null\n) a\nwhere r = 1\nORDER BY total_sale desc\nLIMIT 3"
    }
   ]
  },
  {
   "title": "Laggard Products for Store - ${store_id}",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select product_name as \"Product\", (total_sale/1000000.0) as \"Total Sale(mn $)\"\nFROM ( \nSELECT\n  window_start AS \"time\",\n  product_name,\n  total_sale,\n  rank() over (partition by store_id order by window_start desc) r \nFROM summary\nWHERE\n  $__timeFilter(window_start) and store_id = ${store_id} and product_name is not null\n) a\nwhere r = 1\nORDER BY total_sale\nLIMIT 3"
    }
   ]
  }
 ]
}